import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/Header";
import { neobrutalism } from "@clerk/themes";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MentorAI - AI Career Coach",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: neobrutalism,
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={true}
            disableTransitionOnChange={true}
          >
            {/* header */}
            <Header />
            <main className="pt-16 min-h-[calc(100vh-64px-96px)]">
              {children}
            </main>
            {/* footer */}
            <footer className="bg-muted/50 py-8 mt-auto">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made with ❤️ by {"Rishav"}</p>
              </div>
            </footer>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
